/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __dstm2_file_factory_TransactionalFileWrapperFactory__
#define __dstm2_file_factory_TransactionalFileWrapperFactory__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jlong JNICALL Java_TransactionalIO_core_TransactionalFileWrapperFactory_getINodeNative (JNIEnv *env, jobject, jstring);

JNIEXPORT jint JNICALL Java_TransactionalIO_core_TransactionalFile_nativepread (JNIEnv *env, jobject object2, jbyteArray buff, jlong offset, jint size, jobject object);

JNIEXPORT jint JNICALL Java_TransactionalIO_core_ExtendedTransaction_nativepwrite (JNIEnv *env, jobject object2, jbyteArray buff, jlong offset, jint size, jobject object);
#ifdef __cplusplus
}
#endif

#endif /* __HellWorld__ */
