#include "dstm.h"
#include "ip.h"
#include "clookup.h"
#include "machinepile.h"
#include "mlookup.h"
#include "llookup.h"
#include "plookup.h"
#include "queue.h"
#include <pthread.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <netinet/in.h>
#include <sys/types.h>
#include <unistd.h>
#include <time.h>
#include <string.h>
#include <pthread.h>

#define LISTEN_PORT 2156
#define RECEIVE_BUFFER_SIZE 2048
#define NUM_THREADS 10
#define PREFETCH_CACHE_SIZE 1048576 //1MB

/* Global Variables */
extern int classsize[];
extern primarypfq_t pqueue; // shared prefetch queue
extern mcpileq_t mcqueue;  //Shared queue containing prefetch requests sorted by remote machineids 
pthread_t wthreads[NUM_THREADS]; //Worker threads for working on the prefetch queue
pthread_t tPrefetch;
extern objstr_t *mainobjstore;
objstr_t *prefetchcache;

plistnode_t *createPiles(transrecord_t *);
inline int arrayLength(int *array) {
	int i;
	for(i=0 ;array[i] != -1; i++)
		;
	return i;
}
inline int findmax(int *array, int arraylength) {
	int max, i;
	max = array[0];
	for(i = 0; i < arraylength; i++){
		if(array[i] > max) {
			max = array[i];
		}
	}
	return max;
}
/* This function is a prefetch call generated by the compiler that
 * populates the shared primary prefetch queue*/
void prefetch(int ntuples, unsigned int *oids, short *endoffsets, short *arrayfields) {
	int qnodesize;
	int len = 0;

	/* Allocate for the queue node*/
	char *node;
	qnodesize = sizeof(prefetchqelem_t) + sizeof(int) + ntuples * (sizeof(short) + sizeof(unsigned int)) + endoffsets[ntuples - 1] * sizeof(short); 
	if((node = calloc(1,qnodesize)) == NULL) {
		printf("Calloc Error %s, %d\n", __FILE__, __LINE__);
		return;
	}
	/* Set queue node values */
	len = sizeof(prefetchqelem_t);
	memcpy(node + len, &ntuples, sizeof(int));
	len += sizeof(int);
	memcpy(node + len, oids, ntuples*sizeof(unsigned int));
	len += ntuples * sizeof(unsigned int);
	memcpy(node + len, endoffsets, ntuples*sizeof(short));
	len += ntuples * sizeof(short);
	memcpy(node + len, arrayfields, endoffsets[ntuples-1]*sizeof(short));
	/* Lock and insert into primary prefetch queue */
	pthread_mutex_lock(&pqueue.qlock);
	enqueue((prefetchqelem_t *)node);
	pthread_cond_signal(&pqueue.qcond);
	pthread_mutex_unlock(&pqueue.qlock);
}

/* This function initiates the prefetch thread
 * A queue is shared between the main thread of execution
 * and the prefetch thread to process the prefetch call
 * Call from compiler populates the shared queue with prefetch requests while prefetch thread
 * processes the prefetch requests */
void transInit() {
	int t, rc;
	//Create and initialize prefetch cache structure
	prefetchcache = objstrCreate(PREFETCH_CACHE_SIZE);
	//Create prefetch cache lookup table
	if(prehashCreate(HASH_SIZE, LOADFACTOR))
			return; //Failure
	//Initialize primary shared queue
	queueInit();
	//Initialize machine pile w/prefetch oids and offsets shared queue
	mcpileqInit();
	//Create the primary prefetch thread 
	pthread_create(&tPrefetch, NULL, transPrefetch, NULL);
	//Create and Initialize a pool of threads 
	for(t = 0; t< NUM_THREADS; t++) {
	//	rc = pthread_create(&wthreads[t], NULL, pfqProcess, (void *)t);
		if (rc) {
			printf("Thread create error %s, %d\n", __FILE__, __LINE__);
			return;
		}
	}
}

/* This function stops the threads spawned */
void transExit() {
	int t;
	pthread_cancel(tPrefetch);
	for(t = 0; t < NUM_THREADS; t++)
		pthread_cancel(wthreads[t]);

	return;
}

/* This functions inserts randowm wait delays in the order of msec
 * Mostly used when transaction commits retry*/
void randomdelay(void)
{
	struct timespec req, rem;
	time_t t;

	t = time(NULL);
	req.tv_sec = 0;
	req.tv_nsec = (long)(1000000 + (t%10000000)); //1-11 msec
	nanosleep(&req, &rem);
	return;
}

/* This function initializes things required in the transaction start*/
transrecord_t *transStart()
{
	transrecord_t *tmp = malloc(sizeof(transrecord_t));
	tmp->cache = objstrCreate(1048576);
	tmp->lookupTable = chashCreate(HASH_SIZE, LOADFACTOR);
	
	return tmp;
}

/* This function finds the location of the objects involved in a transaction
 * and returns the pointer to the object if found in a remote location */
objheader_t *transRead(transrecord_t *record, unsigned int oid)
{	
	unsigned int machinenumber;
	objheader_t *tmp, *objheader;
	void *objcopy;
	int size;
	void *buf;
		/* Search local cache */
	if((objheader = (objheader_t *)chashSearch(record->lookupTable, oid)) != NULL){
		return(objheader);
	} else if ((objheader = (objheader_t *) mhashSearch(oid)) != NULL) {
		/* Look up in machine lookup table  and copy  into cache*/
//		tmp = mhashSearch(oid);
		size = sizeof(objheader_t)+classsize[tmp->type];
		objcopy = objstrAlloc(record->cache, size);
		memcpy(objcopy, (void *)objheader, size);
		/* Insert into cache's lookup table */
		chashInsert(record->lookupTable, objheader->oid, objcopy); 
		return(objcopy);
	} else { /* If not found in machine look up */
		/* Get the object from the remote location */
		machinenumber = lhashSearch(oid);
		objcopy = getRemoteObj(record, machinenumber, oid);
		if(objcopy == NULL) {
			//If object is not found in Remote location
			//printf("Object oid = %d not found in Machine %d\n", oid, machinenumber);
			return NULL;
		}
		else {
			//printf("Object oid = %d found in Machine %d\n", oid, machinenumber);
			return(objcopy);
		}
	} 
}

/* This function creates objects in the transaction record */
objheader_t *transCreateObj(transrecord_t *record, unsigned short type)
{
	objheader_t *tmp = (objheader_t *) objstrAlloc(record->cache, (sizeof(objheader_t) + classsize[type]));
	tmp->oid = getNewOID();
	tmp->type = type;
	tmp->version = 1;
	tmp->rcount = 0; //? not sure how to handle this yet
	tmp->status = 0;
	tmp->status |= NEW;
	chashInsert(record->lookupTable, tmp->oid, tmp);
	return tmp;
}

/* This function creates machine piles based on all machines involved in a
 * transaction commit request */
plistnode_t *createPiles(transrecord_t *record) {
	int i = 0;
	unsigned int size;/* Represents number of bins in the chash table */
	chashlistnode_t *curr, *ptr, *next;
	plistnode_t *pile = NULL;
	unsigned int machinenum;
	void *localmachinenum;
	objheader_t *headeraddr;

	ptr = record->lookupTable->table;
	size = record->lookupTable->size;

	for(i = 0; i < size ; i++) {
		curr = &ptr[i];
		/* Inner loop to traverse the linked list of the cache lookupTable */
		while(curr != NULL) {
			//if the first bin in hash table is empty
			if(curr->key == 0) {
				break;
			}
			next = curr->next;
			//Get machine location for object id
			
			if ((machinenum = lhashSearch(curr->key)) == 0) {
			       printf("Error: No such machine %s, %d\n", __FILE__, __LINE__);
			       return NULL;
			}

			if ((headeraddr = chashSearch(record->lookupTable, curr->key)) == NULL) {
				printf("Error: No such oid %s, %d\n", __FILE__, __LINE__);
				return NULL;
			}
			//Make machine groups
			if ((pile = pInsert(pile, headeraddr, machinenum, record->lookupTable->numelements)) == NULL) {
				printf("pInsert error %s, %d\n", __FILE__, __LINE__);
				return NULL;
			}
			
			/* Check if local or not */
			if((localmachinenum = mhashSearch(curr->key)) != NULL) { 
				pile->local = 1; //True i.e. local
			}
		
			curr = next;
		}
	}
	return pile; 
}

/* This function initiates the transaction commit process
 * Spawns threads for each of the new connections with Participants 
 * and creates new piles by calling the createPiles(),
 * Fills the piles with necesaary information and 
 * Sends a transrequest() to each pile*/
int transCommit(transrecord_t *record) {	
	unsigned int tot_bytes_mod, *listmid;
	plistnode_t *pile;
	int i, rc, val;
	int pilecount = 0, offset, threadnum = 0, trecvcount = 0, tmachcount = 0;
	char buffer[RECEIVE_BUFFER_SIZE],control;
	char transid[TID_LEN];
	trans_req_data_t *tosend;
	trans_commit_data_t transinfo;
	static int newtid = 0;
	char treplyctrl = 0, treplyretry = 0; /* keeps track of the common response that needs to be sent */
	char localstat = 0;

	/* Look through all the objects in the transaction record and make piles 
	 * for each machine involved in the transaction*/
	pile = createPiles(record);

	/* Create the packet to be sent in TRANS_REQUEST */

	/* Count the number of participants */
	pilecount = pCount(pile);
		
	/* Create a list of machine ids(Participants) involved in transaction	*/
	if((listmid = calloc(pilecount, sizeof(unsigned int))) == NULL) {
		printf("Calloc error %s, %d\n", __FILE__, __LINE__);
		return 1;
	}		
	pListMid(pile, listmid);
	

	/* Initialize thread variables,
	 * Spawn a thread for each Participant involved in a transaction */
	pthread_t thread[pilecount];
	pthread_attr_t attr;			
	pthread_cond_t tcond;
	pthread_mutex_t tlock;
	pthread_mutex_t tlshrd;
	
	thread_data_array_t *thread_data_array;
	thread_data_array = (thread_data_array_t *) malloc(sizeof(thread_data_array_t)*pilecount);
	local_thread_data_array_t *ltdata;
	if((ltdata = calloc(1, sizeof(local_thread_data_array_t))) == NULL) {
		printf("Calloc error %s, %d\n", __FILE__, __LINE__);
		return 1;
	}

	thread_response_t rcvd_control_msg[pilecount];	/* Shared thread array that keeps track of responses of participants */

	/* Initialize and set thread detach attribute */
	pthread_attr_init(&attr);
	pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_JOINABLE);
	pthread_mutex_init(&tlock, NULL);
	pthread_cond_init(&tcond, NULL);
	
	/* Process each machine pile */
	while(pile != NULL) {
		//Create transaction id
		newtid++;
		//trans_req_data_t *tosend;
		if ((tosend = calloc(1, sizeof(trans_req_data_t))) == NULL) {
			printf("Calloc error %s, %d\n", __FILE__, __LINE__);
			return 1;
		}
		tosend->f.control = TRANS_REQUEST;
		sprintf(tosend->f.trans_id, "%x_%d", pile->mid, newtid);
		tosend->f.mcount = pilecount;
		tosend->f.numread = pile->numread;
		tosend->f.nummod = pile->nummod;
		tosend->f.sum_bytes = pile->sum_bytes;
		tosend->listmid = listmid;
		tosend->objread = pile->objread;
		tosend->oidmod = pile->oidmod;
		thread_data_array[threadnum].thread_id = threadnum;
		thread_data_array[threadnum].mid = pile->mid;
		thread_data_array[threadnum].pilecount = pilecount;
		thread_data_array[threadnum].buffer = tosend;
		thread_data_array[threadnum].recvmsg = rcvd_control_msg;
		thread_data_array[threadnum].threshold = &tcond;
		thread_data_array[threadnum].lock = &tlock;
		thread_data_array[threadnum].count = &trecvcount;
		thread_data_array[threadnum].replyctrl = &treplyctrl;
		thread_data_array[threadnum].replyretry = &treplyretry;
		thread_data_array[threadnum].rec = record;
		/* If local do not create any extra connection */
		if(pile->local != 1) { /* Not local */
			rc = pthread_create(&thread[threadnum], NULL, transRequest, (void *) &thread_data_array[threadnum]);  
			if (rc) {
				perror("Error in pthread create\n");
				return 1;
			}
		} else { /*Local*/
			/*Unset the pile->local flag*/
			pile->local = 0;
			/*Set flag to identify that Local machine is involved*/
			ltdata->tdata = &thread_data_array[threadnum];
			ltdata->transinfo = &transinfo;
			val = pthread_create(&thread[threadnum], NULL, handleLocalReq, (void *) ltdata);
			if (val) {
				perror("Error in pthread create\n");
				return 1;
			}
		}
		threadnum++;		
		pile = pile->next;
	}

	/* Free attribute and wait for the other threads */
	pthread_attr_destroy(&attr);
	for (i = 0 ;i < pilecount ; i++) {
		rc = pthread_join(thread[i], NULL);
		if (rc)
		{
			printf("ERROR return code from pthread_join() is %d\n", rc);
			return 1;
		}
	}
	
	/* Free resources */	
	pthread_cond_destroy(&tcond);
	pthread_mutex_destroy(&tlock);
	free(tosend);
	free(listmid);
	pDelete(pile);
	free(thread_data_array);
	free(ltdata);

	/* Retry trans commit procedure if not sucessful in the first try */
	if(treplyretry == 1) {
		/* wait a random amount of time */
		randomdelay();
		//sleep(1);
		/* Retry the commiting transaction again */
		transCommit(record);
	}	
	
	return 0;
}

/* This function sends information involved in the transaction request and 
 * accepts a response from particpants.
 * It calls decideresponse() to decide on what control message 
 * to send next and sends the message using sendResponse()*/
void *transRequest(void *threadarg) {
	int sd, i, n;
	struct sockaddr_in serv_addr;
	struct hostent *server;
	thread_data_array_t *tdata;
	objheader_t *headeraddr;
	char buffer[RECEIVE_BUFFER_SIZE], control, recvcontrol;
	char machineip[16], retval;

	tdata = (thread_data_array_t *) threadarg;

	/* Send Trans Request */
	if ((sd = socket(AF_INET, SOCK_STREAM, 0)) < 0) {
		perror("Error in socket for TRANS_REQUEST\n");
		return NULL;
	}
	bzero((char*) &serv_addr, sizeof(serv_addr));
	serv_addr.sin_family = AF_INET;
	serv_addr.sin_port = htons(LISTEN_PORT);
	midtoIP(tdata->mid,machineip);
	machineip[15] = '\0';
	serv_addr.sin_addr.s_addr = inet_addr(machineip);
	/* Open Connection */
	if (connect(sd, (struct sockaddr *) &serv_addr, sizeof(struct sockaddr)) < 0) {
		perror("Error in connect for TRANS_REQUEST\n");
		return NULL;
	}
	
	printf("DEBUG-> trans.c Sending TRANS_REQUEST to mid %s\n", machineip);
	/* Send bytes of data with TRANS_REQUEST control message */
	if (send(sd, &(tdata->buffer->f), sizeof(fixed_data_t),MSG_NOSIGNAL) < sizeof(fixed_data_t)) {
		perror("Error sending fixed bytes for thread\n");
		return NULL;
	}
	/* Send list of machines involved in the transaction */
	{
	  int size=sizeof(unsigned int)*tdata->pilecount;
	  if (send(sd, tdata->buffer->listmid, size, MSG_NOSIGNAL) < size) {
	    perror("Error sending list of machines for thread\n");
	    return NULL;
	  }
	}
	/* Send oids and version number tuples for objects that are read */
	{
	  int size=(sizeof(unsigned int)+sizeof(short))*tdata->buffer->f.numread;
	  if (send(sd, tdata->buffer->objread, size, MSG_NOSIGNAL) < size) {
	    perror("Error sending tuples for thread\n");
	    return NULL;
	  }
	}
	/* Send objects that are modified */
	for(i = 0; i < tdata->buffer->f.nummod ; i++) {
	  int size;
	  headeraddr = chashSearch(tdata->rec->lookupTable, tdata->buffer->oidmod[i]);
	  size=sizeof(objheader_t)+classsize[headeraddr->type];
	  if (send(sd, headeraddr, size, MSG_NOSIGNAL)  < size) {
	    perror("Error sending obj modified for thread\n");
	    return NULL;
	  }
	}

	/* Read control message from Participant */
	if((n = read(sd, &control, sizeof(char))) <= 0) {
		perror("Error in reading control message from Participant\n");
		return NULL;
	}
	recvcontrol = control;
	
	/* Update common data structure and increment count */
	tdata->recvmsg[tdata->thread_id].rcv_status = recvcontrol;

	/* Lock and update count */
	//Thread sleeps until all messages from pariticipants are received by coordinator
	pthread_mutex_lock(tdata->lock);

	(*(tdata->count))++; /* keeps track of no of messages received by the coordinator */

	/* Wake up the threads and invoke decideResponse (once) */
	if(*(tdata->count) == tdata->pilecount) {
		if (decideResponse(tdata) != 0) { 
			printf("decideResponse returned error %s,%d\n", __FILE__, __LINE__);
			pthread_mutex_unlock(tdata->lock);
			close(sd);
			return NULL;
		}
		pthread_cond_broadcast(tdata->threshold);
	} else {
		pthread_cond_wait(tdata->threshold, tdata->lock);
	}
	pthread_mutex_unlock(tdata->lock);

	/* Send the final response such as TRANS_COMMIT or TRANS_ABORT t
	 * to all participants in their respective socket */
	if (sendResponse(tdata, sd) == 0) { 
		printf("sendResponse returned error %s,%d\n", __FILE__, __LINE__);
		pthread_mutex_unlock(tdata->lock);
		close(sd);
		return NULL;
	}

	/* Close connection */
	close(sd);
	pthread_exit(NULL);
}

/* This function decides the reponse that needs to be sent to 
 * all Participant machines involved in the transaction commit */
int decideResponse(thread_data_array_t *tdata) {
	char control;
	int i, transagree = 0, transdisagree = 0, transsoftabort = 0; /* Counters to formulate decision of what
									 message to send */

	//Check common data structure 
	for (i = 0 ; i < tdata->pilecount ; i++) {
		/*Switch on response from Participant */
		control = tdata->recvmsg[i].rcv_status; /* tdata: keeps track of all participant responses
							   written onto the shared array */
		switch(control) {
			case TRANS_DISAGREE:
				printf("DEBUG-> trans.c Recv TRANS_DISAGREE\n");
				transdisagree++;
				break;

			case TRANS_AGREE:
				printf("DEBUG-> trans.c Recv TRANS_AGREE\n");
				transagree++;
				break;
				
			case TRANS_SOFT_ABORT:
				printf("DEBUG-> trans.c Recv TRANS_SOFT_ABORT\n");
				transsoftabort++;
				break;
			default:
				printf("Participant sent unknown message in %s, %d\n", __FILE__, __LINE__);
				return -1;
		}
	}
	
	/* Decide what control message to send to Participant */	
	if(transdisagree > 0) {
		/* Send Abort */
		*(tdata->replyctrl) = TRANS_ABORT;
		printf("DEBUG-> trans.c Sending TRANS_ABORT\n");
		objstrDelete(tdata->rec->cache);
		chashDelete(tdata->rec->lookupTable);
		free(tdata->rec);
	} else if(transagree == tdata->pilecount){
		/* Send Commit */
		*(tdata->replyctrl) = TRANS_COMMIT;
		printf("DEBUG-> trans.c Sending TRANS_COMMIT\n");
		objstrDelete(tdata->rec->cache);
		chashDelete(tdata->rec->lookupTable);
		free(tdata->rec);
	} else if(transsoftabort > 0 && transdisagree == 0) {
		/* Send Abort in soft abort case followed by retry commiting transaction again*/
		*(tdata->replyctrl) = TRANS_ABORT;
		*(tdata->replyretry) = 1;
		printf("DEBUG-> trans.c Sending TRANS_ABORT\n");
	} else {
		printf("DEBUG -> %s, %d: Error: undecided response\n", __FILE__, __LINE__);
		return -1;
	}
	
	return 0;
}
/* This function sends the final response to all threads in their respective socket id */
char sendResponse(thread_data_array_t *tdata, int sd) {
	int n, N, sum, oidcount = 0;
	char *ptr, retval = 0;
	unsigned int *oidnotfound;

	/* If the decided response is due to a soft abort and missing objects at the Participant's side */
	if(tdata->recvmsg[tdata->thread_id].rcv_status == TRANS_SOFT_ABORT) {
		/* Read list of objects missing */
		if((read(sd, &oidcount, sizeof(int)) != 0) && (oidcount != 0)) {
			N = oidcount * sizeof(unsigned int);
			if((oidnotfound = calloc(oidcount, sizeof(unsigned int))) == NULL) {
				printf("Calloc error %s, %d\n", __FILE__, __LINE__);
			}
			ptr = (char *) oidnotfound;
			do {
				n = read(sd, ptr+sum, N-sum);
				sum += n;
			} while(sum < N && n !=0);
		}
		retval =  TRANS_SOFT_ABORT;
	}
	/* If the decided response is TRANS_ABORT */
	if(*(tdata->replyctrl) == TRANS_ABORT) {
		retval = TRANS_ABORT;
	} else if(*(tdata->replyctrl) == TRANS_COMMIT) { /* If the decided response is TRANS_COMMIT */
		retval = TRANS_COMMIT;
	}
	/* Send response to the Participant */
	if (send(sd, tdata->replyctrl, sizeof(char),MSG_NOSIGNAL) < sizeof(char)) {
		perror("Error sending ctrl message for participant\n");
	}

	return retval;
}

/* This function opens a connection, places an object read request to the 
 * remote machine, reads the control message and object if available  and 
 * copies the object and its header to the local cache.
 * TODO replace mnum and midtoIP() with MACHINE_IP address later */ 

void *getRemoteObj(transrecord_t *record, unsigned int mnum, unsigned int oid) {
	int sd, size, val;
	struct sockaddr_in serv_addr;
	struct hostent *server;
	char control;
	char machineip[16];
	objheader_t *h;
	void *objcopy;

	if ((sd = socket(AF_INET, SOCK_STREAM, 0)) < 0) {
		perror("Error in socket\n");
		return NULL;
	}
	bzero((char*) &serv_addr, sizeof(serv_addr));
	serv_addr.sin_family = AF_INET;
	serv_addr.sin_port = htons(LISTEN_PORT);
	//serv_addr.sin_addr.s_addr = inet_addr(MACHINE_IP);
	midtoIP(mnum,machineip);
	machineip[15] = '\0';
	serv_addr.sin_addr.s_addr = inet_addr(machineip);
	/* Open connection */
	if (connect(sd, (struct sockaddr *) &serv_addr, sizeof(struct sockaddr)) < 0) {
		perror("Error in connect\n");
		return NULL;
	}
	char readrequest[sizeof(char)+sizeof(unsigned int)];
	readrequest[0] = READ_REQUEST;
	*((unsigned int *)(&readrequest[1])) = oid;
	if (send(sd, &readrequest, sizeof(readrequest), MSG_NOSIGNAL) < sizeof(readrequest)) {
		perror("Error sending message\n");
		return NULL;
	}

#ifdef DEBUG1
	printf("DEBUG -> ready to rcv ...\n");
#endif
	/* Read response from the Participant */
	if((val = read(sd, &control, sizeof(char))) <= 0) {
		perror("No control response for getRemoteObj sent\n");
		return NULL;
	}
	switch(control) {
		case OBJECT_NOT_FOUND:
			printf("DEBUG -> Control OBJECT_NOT_FOUND received\n");
			return NULL;
		case OBJECT_FOUND:
			/* Read object if found into local cache */
			if((val = read(sd, &size, sizeof(int))) <= 0) {
				perror("No size is read from the participant\n");
				return NULL;
			}
			objcopy = objstrAlloc(record->cache, size);
			if((val = read(sd, objcopy, size)) <= 0) {
				perror("No objects are read from the remote participant\n");
				return NULL;
			}
			/* Insert into cache's lookup table */
			chashInsert(record->lookupTable, oid, objcopy); 
			break;
		default:
			printf("Error in recv request from participant on a READ_REQUEST %s, %d\n",__FILE__, __LINE__);
			return NULL;
	}
	/* Close connection */
	close(sd);
	return objcopy;
}

/*This function handles the local trans requests involved in a transaction commiting process
 * makes a decision if the local machine sends AGREE or DISAGREE or SOFT_ABORT
 * Activates the other nonlocal threads that are waiting for the decision and the
 * based on common decision by all groups involved in the transaction it 
 * either commits or aborts the transaction.
 * It also frees the calloced memory resources
 */

void *handleLocalReq(void *threadarg) {
	int val, i = 0;
	short version;
	char control = 0, *ptr;
	unsigned int oid;
	unsigned int *oidnotfound = NULL, *oidlocked = NULL, *oidmod = NULL;
	void *mobj, *modptr;
	objheader_t *headptr;
	local_thread_data_array_t *localtdata;

	localtdata = (local_thread_data_array_t *) threadarg;

	/* Counters and arrays to formulate decision on control message to be sent */
	oidnotfound = (unsigned int *) calloc((localtdata->tdata->buffer->f.numread + localtdata->tdata->buffer->f.nummod), sizeof(unsigned int));
	oidlocked = (unsigned int *) calloc((localtdata->tdata->buffer->f.numread + localtdata->tdata->buffer->f.nummod), sizeof(unsigned int));
	oidmod = (unsigned int *) calloc(localtdata->tdata->buffer->f.nummod, sizeof(unsigned int));
	int objnotfound = 0, objlocked = 0, objmod =0, v_nomatch = 0, v_matchlock = 0, v_matchnolock = 0;
	int objmodnotfound = 0, nummodfound = 0;

	/* modptr points to the beginning of the object store 
	 * created at the Pariticipant */ 
	if ((modptr = objstrAlloc(mainobjstore, localtdata->tdata->buffer->f.sum_bytes)) == NULL) {
		printf("objstrAlloc error for modified objects %s, %d\n", __FILE__, __LINE__);
		return NULL;
	}

	ptr = modptr;

	/* Process each oid in the machine pile/ group per thread */
	for (i = 0; i < localtdata->tdata->buffer->f.numread + localtdata->tdata->buffer->f.nummod; i++) {
		if (i < localtdata->tdata->buffer->f.numread) {//Objs only read and not modified
			int incr = sizeof(unsigned int) + sizeof(short);// Offset that points to next position in the objread array
			incr *= i;
			oid = *((unsigned int *)(localtdata->tdata->buffer->objread + incr));
			incr += sizeof(unsigned int);
			version = *((short *)(localtdata->tdata->buffer->objread + incr));
		} else {//Objs modified
			headptr = (objheader_t *) ptr;
			oid = headptr->oid;
			oidmod[objmod] = oid;//Array containing modified oids
			objmod++;
			version = headptr->version;
			ptr += sizeof(objheader_t) + classsize[headptr->type];
		}

		/* Check if object is still present in the machine since the beginning of TRANS_REQUEST */

		/* Save the oids not found and number of oids not found for later use */
		if ((mobj = mhashSearch(oid)) == NULL) {/* Obj not found */
			/* Save the oids not found and number of oids not found for later use */

			oidnotfound[objnotfound] = ((objheader_t *)mobj)->oid;
			objnotfound++;
		} else { /* If Obj found in machine (i.e. has not moved) */
			/* Check if Obj is locked by any previous transaction */
			if ((((objheader_t *)mobj)->status & LOCK) == LOCK) {
				if (version == ((objheader_t *)mobj)->version) {      /* If not locked then match versions */ 
					v_matchlock++;
				} else {/* If versions don't match ...HARD ABORT */
					v_nomatch++;
					/* Send TRANS_DISAGREE to Coordinator */
					localtdata->tdata->recvmsg[localtdata->tdata->thread_id].rcv_status = TRANS_DISAGREE;
					printf("DEBUG -> Sending TRANS_DISAGREE\n");
					//return tdata->recvmsg[tdata->thread_id].rcv_status;  
				}
			} else {/* If Obj is not locked then lock object */
				((objheader_t *)mobj)->status |= LOCK;
				//TODO Remove this for Testing
				randomdelay();

				/* Save all object oids that are locked on this machine during this transaction request call */
				oidlocked[objlocked] = ((objheader_t *)mobj)->oid;
				objlocked++;
				if (version == ((objheader_t *)mobj)->version) { /* Check if versions match */
					v_matchnolock++;
				} else { /* If versions don't match ...HARD ABORT */
					v_nomatch++;
					/* Send TRANS_DISAGREE to Coordinator */
					localtdata->tdata->recvmsg[localtdata->tdata->thread_id].rcv_status = TRANS_DISAGREE;
					printf("DEBUG -> Sending TRANS_DISAGREE\n");
				//	return tdata->recvmsg[tdata->thread_id].rcv_status;  
				}
			}
		}
	}

	/*Decide the response to be sent to the Coordinator( the local machine in this case)*/

	/* Condition to send TRANS_AGREE */
	if(v_matchnolock == localtdata->tdata->buffer->f.numread + localtdata->tdata->buffer->f.nummod) {
		localtdata->tdata->recvmsg[localtdata->tdata->thread_id].rcv_status = TRANS_AGREE;
		printf("DEBUG -> Sending TRANS_AGREE\n");
	}
	/* Condition to send TRANS_SOFT_ABORT */
	if((v_matchlock > 0 && v_nomatch == 0) || (objnotfound > 0 && v_nomatch == 0)) {
		localtdata->tdata->recvmsg[localtdata->tdata->thread_id].rcv_status = TRANS_SOFT_ABORT;
		printf("DEBUG -> Sending TRANS_SOFT_ABORT\n");
		/* Send number of oids not found and the missing oids if objects are missing in the machine */
		/* TODO Remember to store the oidnotfound for later use
		if(objnotfound != 0) {
			int size = sizeof(unsigned int)* objnotfound;
		}
		*/
	}

	/* Fill out the trans_commit_data_t data structure. This is required for a trans commit process
	 * if Participant receives a TRANS_COMMIT */
	localtdata->transinfo->objmod = oidmod;
	localtdata->transinfo->objlocked = oidlocked;
	localtdata->transinfo->objnotfound = oidnotfound;
	localtdata->transinfo->modptr = modptr;
	localtdata->transinfo->nummod = localtdata->tdata->buffer->f.nummod;
	localtdata->transinfo->numlocked = objlocked;
	localtdata->transinfo->numnotfound = objnotfound;

	/*Set flag to show that common data structure for this individual thread has been written to */
	//*(tdata->localstatus) |= LM_UPDATED;
	
	/* Lock and update count */
	//Thread sleeps until all messages from pariticipants are received by coordinator
	pthread_mutex_lock(localtdata->tdata->lock);
	(*(localtdata->tdata->count))++; /* keeps track of no of messages received by the coordinator */

	/* Wake up the threads and invoke decideResponse (once) */
	if(*(localtdata->tdata->count) == localtdata->tdata->pilecount) {
		if (decideResponse(localtdata->tdata) != 0) { 
			printf("decideResponse returned error %s,%d\n", __FILE__, __LINE__);
			pthread_mutex_unlock(localtdata->tdata->lock);
			return NULL;
		}
		pthread_cond_broadcast(localtdata->tdata->threshold);
	} else {
		pthread_cond_wait(localtdata->tdata->threshold, localtdata->tdata->lock);
	}
	pthread_mutex_unlock(localtdata->tdata->lock);

	/*Based on DecideResponse(), Either COMMIT or ABORT the operation*/
	if(*(localtdata->tdata->replyctrl) == TRANS_ABORT){
		if(transAbortProcess(modptr,oidlocked, localtdata->transinfo->numlocked, localtdata->transinfo->nummod, localtdata->tdata->buffer->f.numread) != 0) {
			printf("Error in transAbortProcess() %s,%d\n", __FILE__, __LINE__);
			return NULL;
		}
	}else if(*(localtdata->tdata->replyctrl) == TRANS_COMMIT){
		if(transComProcess(localtdata->transinfo) != 0) {
			printf("Error in transComProcess() %s,%d\n", __FILE__, __LINE__);
			return NULL;
		}
	}

	/* Free memory */
	printf("DEBUG -> Freeing...\n");
	fflush(stdout);
	if (localtdata->transinfo->objmod != NULL) {
		free(localtdata->transinfo->objmod);
		localtdata->transinfo->objmod = NULL;
	}
	if (localtdata->transinfo->objlocked != NULL) {
		free(localtdata->transinfo->objlocked);
		localtdata->transinfo->objlocked = NULL;
	}
	if (localtdata->transinfo->objnotfound != NULL) {
		free(localtdata->transinfo->objnotfound);
		localtdata->transinfo->objnotfound = NULL;
	}
	
	pthread_exit(NULL);
}
/* This function completes the ABORT process if the transaction is aborting 
 */
int transAbortProcess(void *modptr, unsigned int *objlocked, int numlocked, int nummod, int numread) {
	char *ptr;
	int i;
	objheader_t *tmp_header;
	void *header;

	printf("DEBUG -> Recv TRANS_ABORT\n");
	/* Set all ref counts as 1 and do garbage collection */
	ptr = modptr;
	for(i = 0; i< nummod; i++) {
		tmp_header = (objheader_t *)ptr;
		tmp_header->rcount = 1;
		ptr += sizeof(objheader_t) + classsize[tmp_header->type];
	}
	/* Unlock objects that was locked due to this transaction */
	for(i = 0; i< numlocked; i++) {
		header = mhashSearch(objlocked[i]);// find the header address
		((objheader_t *)header)->status &= ~(LOCK);
	}
	//TODO/* Unset the bit for local objects */

	/* Send ack to Coordinator */
	printf("DEBUG-> TRANS_SUCCESSFUL\n");

	/*Free the pointer */
	ptr = NULL;
	return 0;
}

/*This function completes the COMMIT process is the transaction is commiting
 */
 int transComProcess(trans_commit_data_t *transinfo) {
	 objheader_t *header;
	 int i = 0, offset = 0;
	 char control;
	 
	 printf("DEBUG -> Recv TRANS_COMMIT\n");
	 /* Process each modified object saved in the mainobject store */
	 for(i=0; i<transinfo->nummod; i++) {
		 if((header = (objheader_t *) mhashSearch(transinfo->objmod[i])) == NULL) {
			 printf("mhashsearch returns NULL at %s, %d\n", __FILE__, __LINE__);
		 }
		 /* Change reference count of older address and free space in objstr ?? */
		 header->rcount = 1; //TODO Not sure what would be the val

		 /* Change ptr address in mhash table */
		 mhashRemove(transinfo->objmod[i]);
		 mhashInsert(transinfo->objmod[i], (transinfo->modptr + offset));
		 offset += sizeof(objheader_t) + classsize[header->type];

		 /* Update object version number */
		 header = (objheader_t *) mhashSearch(transinfo->objmod[i]);
		 header->version += 1;
	 }

	 /* Unlock locked objects */
	 for(i=0; i<transinfo->numlocked; i++) {
		 header = (objheader_t *) mhashSearch(transinfo->objlocked[i]);
		 header->status &= ~(LOCK);
	 }

	 //TODO Update location lookup table
	 //TODO/* Unset the bit for local objects */

	 /* Send ack to Coordinator */
	 printf("DEBUG-> TRANS_SUCESSFUL\n");
	 return 0;
 }

/* This function checks if the prefetch oids are same and have same offsets  
 * for case x.a.b and y.a.b where x and y have same oid's
 * or if a.b.c is a subset of x.b.c.d*/ 
/* check for case where the generated request a.y.z or x.y.z.g then 
 * prefetch needs to be generated for x.y.z.g  if oid of a and x are same*/
void checkPrefetchTuples(prefetchqelem_t *node) {
	int i,j, count,k, sindex, index;
	char *ptr, *tmp;
	int ntuples, slength;
	unsigned int *oid;
	short *endoffsets, *arryfields; 

	/* Check for the case x.y.z and a.b.c are same oids */ 
 	ptr = (char *) node;
	ntuples = *(GET_NTUPLES(ptr));
	oid = GET_PTR_OID(ptr);
	endoffsets = GET_PTR_EOFF(ptr, ntuples); 
	arryfields = GET_PTR_ARRYFLD(ptr, ntuples);
	/* Find offset length for each tuple */
	int numoffset[ntuples];
	numoffset[0] = endoffsets[0];
	for(i = 1; i<ntuples; i++) {
		numoffset[i] = endoffsets[i] - endoffsets[i-1];
	}
	/* Check for redundant tuples by comparing oids of each tuple */
	for(i = 0; i < ntuples; i++) {
		if(oid[i] == -1)
			continue;
		for(j = i+1 ; j < ntuples; j++) {
			if(oid[j] == -1)
				continue;
			/*If oids of tuples match */ 
			if (oid[i] == oid[j]) {
				/* Find the smallest offset length of two tuples*/
				if(numoffset[i] >  numoffset[j]){
					slength = numoffset[j];
					sindex = j;
				}
				else {
					slength = numoffset[i];
					sindex = i;
				}

				/* Compare the offset values based on the current indices
				 * break if they do not match
				 * if all offset values match then pick the largest tuple*/

				if(i == 0) {
					k = 0;
					index = endoffsets[j -1];
					for(count = 0; count < slength; count ++) {
						if (arryfields[k] != arryfields[index]) { 
							break;
						}
						index++;
						k++;
					}	
				} else {
					k = endoffsets[i-1];
					index = endoffsets[j-1];
					printf("Value of slength = %d\n", slength);
					for(count = 0; count < slength; count++) {
						if(arryfields[k] != arryfields[index]) {
							break;
						}
						index++;
						k++;
					}
				}

				if(slength == count) {
					oid[sindex] = -1;
				}
			}
		}
	}
}

void checkPreCache(prefetchqelem_t *node, int *numoffset, int counter, int loopcount, unsigned int objoid, int index, int iter, int oidnfound) {
	char *ptr, *tmp;
	int ntuples, i, k, flag;
	unsigned int * oid;
	short *endoffsets, *arryfields;
	objheader_t *header;

	ptr = (char *) node;
	ntuples = *(GET_NTUPLES(ptr));
	oid = GET_PTR_OID(ptr);
	endoffsets = GET_PTR_EOFF(ptr, ntuples);
	arryfields = GET_PTR_ARRYFLD(ptr, ntuples);

	if(oidnfound == 1) {
		if((header = (objheader_t *) prehashSearch(objoid)) == NULL) {
			return;
		} else { //Found in Prefetch Cache
			//TODO Decide if object is too old, if old remove from cache
			tmp = (char *) header;
			/* Check if any of the offset oid is available in the Prefetch cache */
			for(i = counter; i < loopcount; i++) {
				objoid = *(tmp + sizeof(objheader_t) + arryfields[counter]);
				if((header = (objheader_t *)prehashSearch(objoid)) != NULL) {
					flag = 0;
				} else {
					flag = 1;
					break;
				}
			}
		}
	} else {
		for(i = counter; i<loopcount; i++) {
			if((header = (objheader_t *)prehashSearch(objoid)) != NULL) {
				tmp = (char *) header;
				objoid = *(tmp + sizeof(objheader_t) + arryfields[index]);
				flag = 0;
				index++;
			} else {
				flag = 1;
				break;
			}
		}
	}

	/* If oid not found locally or in prefetch cache then 
	 * assign the latest oid found as the new oid 
	 * and copy left over offsets into the arrayoffsetfieldarray*/
	oid[iter] = objoid;
	numoffset[iter] = numoffset[iter] - (i+1);
	for(k = 0; k < numoffset[iter] ; k++) {
		arryfields[endoffsets[counter]+k] = arryfields[endoffsets[counter]+k+1];
	}

	if(flag == 0) {
		oid[iter] = -1;
		numoffset[iter] = 0;
	}
}

/* This function makes machine piles to be added into the machine pile queue for each prefetch call */
prefetchpile_t *makePreGroups(prefetchqelem_t *node, int *numoffset) {
	char *ptr, *tmp;
	int ntuples, slength, i, machinenum;
	int maxoffset;
	unsigned int *oid;
	short *endoffsets, *arryfields, *offset; 
	prefetchpile_t *head = NULL;

	/* Check for the case x.y.z and a.b.c are same oids */ 
 	ptr = (char *) node;
	ntuples = *(GET_NTUPLES(ptr));
	oid = GET_PTR_OID(ptr);
	endoffsets = GET_PTR_EOFF(ptr, ntuples); 
	arryfields = GET_PTR_ARRYFLD(ptr, ntuples);

	/* Check for redundant tuples by comparing oids of each tuple */
	for(i = 0; i < ntuples; i++) {
		if(oid[i] == -1)
			continue;
		/* For each tuple make piles */
		if ((machinenum = lhashSearch(oid[i])) == 0) {
			printf("Error: No such Machine %s, %d\n", __FILE__, __LINE__);
			return NULL;
		}
		/* Insert into machine pile */
		offset = &arryfields[endoffsets[i-1]];
		insertPile(machinenum, oid[i], numoffset[i], offset, head);
	}

	return head;
}


/* This function checks if the oids within the prefetch tuples are available locally.
 * If yes then makes the tuple invalid. If no then rearranges oid and offset values in 
 * the prefetchqelem_t node to represent a new prefetch tuple */
prefetchpile_t *foundLocal(prefetchqelem_t *node) {
	int ntuples,i, j, k, oidnfound = 0, index, flag;
	unsigned int *oid;
	unsigned int  objoid;
	char *ptr, *tmp;
	objheader_t *objheader;
	short *endoffsets, *arryfields; 
	prefetchpile_t *head = NULL;

 	ptr = (char *) node;
	ntuples = *(GET_NTUPLES(ptr));
	oid = GET_PTR_OID(ptr);
	endoffsets = GET_PTR_EOFF(ptr, ntuples); 
	arryfields = GET_PTR_ARRYFLD(ptr, ntuples);
	/* Find offset length for each tuple */
	int numoffset[ntuples];//Number of offsets for each tuple
	numoffset[0] = endoffsets[0];
	for(i = 1; i<ntuples; i++) {
		numoffset[i] = endoffsets[i] - endoffsets[i-1];
	}
	for(i = 0; i < ntuples; i++) { 
		if(oid[i] == -1)
			continue;
		/* If object found locally */
		if((objheader = (objheader_t*) mhashSearch(oid[i])) != NULL) { 
			oidnfound = 0;
			tmp = (char *) objheader;
			/* Find the oid of its offset value */
			if(i == 0) 
				index = 0;
			else 
				index = endoffsets[i - 1];
			for(j = 0 ; j < numoffset[i] ; j++) {
				objoid = *(tmp + sizeof(objheader_t) + arryfields[index]);
				/*If oid found locally then 
				 *assign the latest oid found as the new oid 
				 *and copy left over offsets into the arrayoffsetfieldarray*/
				oid[i] = objoid;
				numoffset[i] = numoffset[i] - (j+1);
				for(k = 0; k < numoffset[i]; k++)
					arryfields[endoffsets[j]+ k] = arryfields[endoffsets[j]+k+1];
				index++;
				/*New offset oid not found */
				if((objheader = (objheader_t*) mhashSearch(objoid)) == NULL) {
					flag = 1;
					checkPreCache(node, numoffset, j, numoffset[i], objoid, index, i, oidnfound); 
					break;
				} else 
					flag = 0;
			}
		
			/*If all offset oids are found locally,make the prefetch tuple invalid */
			if(flag == 0) {
				oid[i] = -1;
				numoffset[i] = 0;
			}
		} else {
			oidnfound = 1;
			/* Look in Prefetch cache */
			checkPreCache(node, numoffset, 0, numoffset[i], oid[i], 0, i, oidnfound); 
		}

	}
	/* Make machine groups */
	head = makePreGroups(node, numoffset);
	return head;
}

/* This function is called by the thread calling transPrefetch */
void *transPrefetch(void *t) {
	//int *offstarray = NULL;
	prefetchqelem_t *qnode;
	prefetchpile_t *pilehead = NULL;

	while(1) {
		/* lock mutex of primary prefetch queue */
		pthread_mutex_lock(&pqueue.qlock);
		/* while primary queue is empty, then wait */
		while((pqueue.front == NULL) && (pqueue.rear == NULL)) {
			pthread_cond_wait(&pqueue.qcond, &pqueue.qlock);
		}

		/* dequeue node to create a machine piles and  finally unlock mutex */
		if((qnode = dequeue()) == NULL) {
			printf("Error: No node returned %s, %d\n", __FILE__, __LINE__);
			return NULL;
		}
		pthread_mutex_unlock(&pqueue.qlock);
		/* Reduce redundant prefetch requests */
		checkPrefetchTuples(qnode);
		/* Check if the tuples are found locally, if yes then reduce them further*/ 
		/* and group requests by remote machine ids by calling the makePreGroups() */
		pilehead = foundLocal(qnode);
		
		/* Lock mutex of pool queue */
		pthread_mutex_lock(&mcqueue.qlock);
		/* Update the pool queue with the new remote machine piles generated per prefetch call */
		mcpileenqueue(pilehead);
		/* Broadcast signal on pool queue */
		pthread_cond_broadcast(&mcqueue.qcond);
		/* Unlock mutex of pool queue */
		pthread_mutex_unlock(&mcqueue.qlock);
	}
}

/*This function is called by the thread that processes the 
 * prefetch request makes piles to prefetch records and prefetches the oids from remote machines */
int transPrefetchProcess(transrecord_t *record, int *arrayofoffset[], short numoids){
	int i, k = 0, rc;
	int arraylength[numoids];
	unsigned int machinenumber;
	objheader_t *tmp, *objheader;
	void *objcopy;
	int size;
	pthread_attr_t attr;

	/* Given tuple find length of tuple*/
	for(i = 0; i < numoids ; i++) {
		arraylength[i] = arrayLength(arrayofoffset[i]);
	}

	/* Initialize and set thread attributes 
	 * Spawn a thread for each prefetch request sent*/
	pthread_t thread[numoids];
	pthread_attr_init(&attr);
	pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_JOINABLE);
		
	/* Create  Machine Piles to send prefetch requests use threads*/
	for( i = 0 ; i< numoids ; i++) {
		if(arrayofoffset[i][0] == -1) 
			continue;
		else{
			/* For each Pile in the machine send TRANS_PREFETCH */
			//makePiles(arrayofoffset, numoids);
			/* Fill thread data structure */
			rc = pthread_create(&thread[i] , &attr, sendPrefetchReq, (void *) arrayofoffset[i]);
			if (rc) {
				perror("Error in pthread create at transPrefetchProcess()\n");
				return 1;
			}

		}
	}

	/* Free attribute and wait to join other threads */
	for (i = 0 ;i < numoids ; i++) {
		rc = pthread_join(thread[i], NULL);
		if (rc) {
			perror("Error pthread_join() in transPrefetchProcess()\n");
			return 1;
		}
	}
	pthread_attr_destroy(&attr);
	
	return 0;
		
}

void *sendPrefetchReq(void *prefetchtuple) {
	int sd, i;
	struct sockaddr_in serv_addr;
	struct hostent *server;
	char buffer[RECEIVE_BUFFER_SIZE], control, recvcontrol;
	char machineip[16], retval;


	/* Send Trans Prefetch Request */
	if ((sd = socket(AF_INET, SOCK_STREAM, 0)) < 0) {
		perror("Error in socket for TRANS_REQUEST\n");
		return NULL;
	}
	bzero((char*) &serv_addr, sizeof(serv_addr));
	serv_addr.sin_family = AF_INET;
	serv_addr.sin_port = htons(LISTEN_PORT);
	//midtoIP(tdata->mid,machineip);
//	machineip[15] = '\0';
//	serv_addr.sin_addr.s_addr = inet_addr(machineip);

	/* Open Connection */
	if (connect(sd, (struct sockaddr *) &serv_addr, sizeof(struct sockaddr)) < 0) {
		perror("Error in connect for TRANS_REQUEST\n");
		return NULL;
	}

	close(sd);
	pthread_exit(NULL);

}
