#!/bin/bash
ARG1=$1
ARG2=$2
shift
shift

dir=`pwd`

echo Doing Test $ARG1
../buildscript -64bit -debug -joptimize -robustroot ${dir}/../ -mac -mainclass $ARG1 $ARG2 -o $ARG1
$ARG1.bin $@ &> output/$ARG1.output
diff output/$ARG1.output output/$ARG1.output.goal
rm $ARG1.bin
