#!/bin/bash
export PATH=$PATH:./
dotest Array Array.java
dotest Array2 Array2.java
dotest BoundsFail BoundsFail.java
dotest BoundsFail2 BoundsFail2.java
dotest BoundsFail3 BoundsFail3.java
dotest BoundsFail4 BoundsFail4.java
dotest StringTest StringTest.java
dotest StringBufferTest StringBufferTest.java
dotest Test Test.java
dotest virtualcalltest virtualcalltest.java
dotest IncTest IncTest.java
dotest CommandLineTest CommandLineTest.java hello hi
dotest WriteFile WriteFile.java
dotest ReadFile ReadFile.java
dotest FileLength FileLength.java
dotest IntegerTest IntegerTest.java
dotest InitializerTest InitializerTest.java