#!/bin/bash
export PATH=$PATH:./
dotest Array Array.java
dotest Array2 Array2.java
dotest BoundsFail BoundsFail.java
dotest BoundsFail2 BoundsFail2.java
dotest BoundsFail3 BoundsFail3.java
dotest BoundsFail4 BoundsFail4.java
dotest StringTest StringTest.java
dotest StringBufferTest StringBufferTest.java
dotest Test Test.java
dotest virtualcalltest virtualcalltest.java
dotest IncTest IncTest.java
dotest CommandLineTest CommandLineTest.java hello hi
dotest WriteFile WriteFile.java
dotest ReadFile ReadFile.java
dotest FileLength FileLength.java
dotest IntegerTest IntegerTest.java
dotest AbstractTest AbstractTest.java
dotest EnumTest EnumTest.java
dotest InitializerTest InitializerTest.java
dotest ArrayInitializerTest ArrayInitializerTest.java
dotest InterfaceTest InterfaceTest.java
dotest StaticInnerClassTest StaticInnerClassTest.java
dotest StaticTest StaticTest.java
dotest SwitchCaseTest SwitchCaseTest.java
dotest TryCatchTest TryCatchTest.java
dotest inner inner.java innerp.java innerpt.java innerCallback.java innerEgg2.java innerBigEgg2.java
