#!/bin/bash
ARG1=$1
ARG2=$2
shift
shift

echo Doing Test $ARG1
../buildscript $ARG1 $ARG2 &>/dev/null
$ARG1.bin $@ &> output/$ARG1.output
diff output/$ARG1.output output/$ARG1.output.goal
rm $ARG1.bin
