#!/bin/bash
if [ -n $DISABLEAFID ]
then
java $@
else
if [ -a ~/.AFID/SaveTestCase ]
then 
if [ -z $OLDPATH ]
then
export OLDPATH=$PATH
export PATH=$PATH:~/.AFID/
if [ ! -a ~/research/Robust/.afidconfig ]
then
echo "project=Compiler" > ~/research/Robust/.afidconfig
echo "user=$USER" >> ~/research/Robust/.afidconfig
echo "text/visual=visual" >> ~/research/Robust/.afidconfig
echo "postURL=http://afid.eecs.uci.edu/afid/upload_file.php" >> ~/research/Robust/.afidconfig
~/.AFID/SaveTestCase --create-exclude-file
fi
~/.AFID/SaveTestCase java $@
else
java $@
fi
else
java $@
fi
fi