/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __dstm2_file_factory_HelloWorld__
#define __dstm2_file_factory_HelloWorld__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT void JNICALL Java_dstm2_file_factory_HelloWorld_displayMessage (JNIEnv *env, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __dstm2_file_factory_HelloWorld__ */
