/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __test2_Main__
#define __test2_Main__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jlong JNICALL test2_Main_getINodeNative (JNIEnv *env, jobject, jstring);

#ifdef __cplusplus
}
#endif

#endif /* __HellWorld__ */
