#ifndef BAMBOO_MULTICORE_MEM_HELPER_H
#define BAMBOO_MULTICORE_MEM_HELPER_H

void buildCore2Test();

#define NUM_CORES2TEST 8
int core2test[NUMCORES4GC][NUM_CORES2TEST];

#endif // BAMBOO_MULTICORE_MEM_HELPER_H
